name: DevTest
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master
jobs:
  docker-jetson-build:
    runs-on: [self-hosted, Linux, ARM64, jetson]
    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Fetch GIT LFS
      run: git lfs checkout && git lfs pull
    - name: Install Pytest 
      run: pip3 install pytest 
    - name: Install Wget
      run: pip3 install wget
    - name: Install PIL
      run: pip3 install pillow
    - name: Download Binary Dependencies
      run: python3 download_dependencies.py
    - name: Clean DeepStack Container
      run: docker container rm -f deepstack
      continue-on-error: true
    - name: Build DeepStack jetson Version
      run: docker build -t deepquestai/deepstack:jetson . -f Dockerfile.gpu-jetpack
    - name: Test Scene
      run: |
        docker run --gpus all -d --name deepstack -e VISION-SCENE=True -p 80:5000 deepquestai/deepstack:jetson
        cd tests
        export TEST_DATA_DIR=$PWD"/test_data"
        export TEST_DEEPSTACK_URL="http://localhost:80"
        cd scene
        python3 -m pytest
        docker container rm -f deepstack
    
    - name: Test Detection
      run: |
        docker run --gpus all -d --name deepstack -e VISION-DETECTION=True -p 80:5000 deepquestai/deepstack:jetson
        cd tests
        export TEST_DATA_DIR=$PWD"/test_data"
        export TEST_DEEPSTACK_URL="http://localhost:80"
        cd detection
        python3 -m pytest
        docker container rm -f deepstack

    - name: Test Face
      run: |
        docker run --gpus all -d --name deepstack -e VISION-FACE=True -p 80:5000 deepquestai/deepstack:jetson
        cd tests
        export TEST_DATA_DIR=$PWD"/test_data"
        export TEST_DEEPSTACK_URL="http://localhost:80"
        cd face
        python3 -m pytest
        docker container rm -f deepstack

    - name: Test Custom Detection
      run: |
        cd tests
        modeldir=$(pwd)
        docker run --gpus all -d --name deepstack -v $modeldir/"test_data":/modelstore/detection -p 80:5000 deepquestai/deepstack:jetson
        export TEST_DATA_DIR=$PWD"/test_data"
        export TEST_DEEPSTACK_URL="http://localhost:80" 
        cd custom
        python3 -m pytest
        docker container rm -f deepstack
    - name: Clean DeepStack jetson Version
      run: docker image rm -f deepquestai/deepstack:jetson
