name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: ['arm-rpi','arm64-cpu','arm64-rpi','cpu','gpu','gpu-jetpack']
        include:
            - system: arm-rpi
              arch: linux/arm/v7
            - system: arm64-cpu
              arch: linux/amd64
            - system: arm64-rpi
              arch: linux/arm64
            - system: cpu
              arch: linux/amd64
            - system: gpu
              arch: linux/amd64
            - system: gpu-jetpack
              arch: linux/amd64
      fail-fast: false
    steps:
    - id: lowercaseRepo
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create short sha and tag
      shell: bash
      run: |
        echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
        if [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then echo TAG=latest; else echo TAG="${GITHUB_REF##*/}"; fi >> $GITHUB_ENV
    - name: Build Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.${{ matrix.system }}
        push: true
        tags: |
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:${{ matrix.system }}-${{ env.SHORT_SHA }}
          ghcr.io/${{ steps.lowercaseRepo.outputs.lowercase }}:${{ matrix.system }}-${{ env.TAG }}
        platforms: ${{ matrix.arch }}
        cache-from: type=gha,scope=${{ matrix.system }}
        cache-to: type=gha,mode=max,scope=${{ matrix.system }}
      